### ISSUE TITLE
ngx-disqus module in ionic v3 only displays one thread

### ISSUE THREAD

**Issue by VanSan888** [MurhafSousli/ngx-disqus#19]
I have imported ngx-disqus module to the page.module.ts in my ionic v3 progressive web app like this:
`import { DisqusModule } from 'ngx-disqus';
 
@NgModule({
  declarations: [
    SzenarioerstellungPage,
  ],
  imports: [
    IonicPageModule.forChild(SzenarioerstellungPage),
    DisqusModule.forRoot('my_shortname'),
  ],
  exports: [
    SzenarioerstellungPage
  ]
})
export class SzenarioerstellungPageModule {}`

This is how I use it in mypage.html file:

`<disqus  [identifier] = "pageId" ></disqus>`

And this is how I set the `pageId`:

`ionViewDidLoad() {
    this.szenarioProvider.getUserID().then( UID => {
      this.pageId = UID;
    });

  }`

As you can see, I want to use the unique ID of the user (which he got from firebase authentification) to display a unique discus-thread on his page.

The problem is now that no matter what user gets to this page, discus only shows one and the same thread, instead of individual threads for each user.

Note: no matter what user enters the mentioned page, it always has the same URL (ionic does it like this.): http://localhost:8100/#/szenarioerstellung

But I thought, that the unique [indentifier] would solve this problem.

Do you know, what I did wrong or what I need to add/ have in mind?

**Comment by MurhafSousli** [comment]
**DISQUS** does NOT work when the `#` is used in the router.

for example the URL `http://localhost:8100/#/szenarioerstellung` is read as `http://localhost:8100/`, so no matter how the URL changes, it will still look the same on DISQUS side.

There are 2 solutions:

1 - Find a way to configure your router to use the hashbang `#!` instead of `#`

2 - Disable the `HashLocationStrategy` from the Router so it becomes like the standard URL `http://localhost:8100/szenarioerstellung`.

Read the requirement section in [Using Disqus on AJAX sites](https://help.disqus.com/customer/portal/articles/472107-using-disqus-on-ajax-sites)



  [1]: https://i.stack.imgur.com/xH0ny.png

**Comment by VanSan888** [comment]
I used `import { Routes, RouterModule } from '@angular/router';` to avoid the # in the URL. But Nevertheless disqus only displayed one thread. So I think that the # cannot be the only problem.

Do you have any suggestions?

**Comment by MurhafSousli** [comment]
@VanSan888 Sorry for late response.
Actually It is the only problem, your disqus is getting the same URL again and again, that is why it is giving you the same thread.

It is an incompatibility between Disqus and Ionic

  - DISQUS uses either a standard HTML5 path or a full hash bang path `#!`, see the [docs](https://help.disqus.com/customer/portal/articles/472107-using-disqus-on-ajax-sites).
 - Ionic uses the hash location strategy (I didn't investigate much but I haven't found a way to disable the `#` in ionic)

**Comment by VanSan888** [comment]
Hello Murhaf,
thank you for your reply. I solved this problem by using another webpage
(URL = www.test.de) which isn't using Disqus.
The urls, which I am using are always consisting of this URL plus the
unique ID of the user("www.test.de/UDLIbajha678baj"). The indentifier also
is the unique ID of the user(UDLIbajha678baj). This is definitely not a
good solution, but as I am only developing a prototype for my Masterthesis
it is ok for now.

Actually I could not make Comment-Count work (
https://github.com/MurhafSousli/ngx-disqus/issues/20)... I would really
appreciate, if you would find a solution for this. (direct jsonp request
didn't work for me...)

Best wishes
