### ISSUE TITLE
Disqus module show the wrong language

### ISSUE THREAD

**Issue by manhlinhnguyen** [MurhafSousli/ngx-disqus#2]
Hi! I use your module in my project. It nicely show the disqus comment, however the interface is always in Portugal (pretty weird), although I set the Language in my admin page is "English" and I don't bind anything to attribute [lang]. I also see your code but can not find any hard code.
Do you have any idea? Thanks and look forward to your reply!

**Comment by manhlinhnguyen** [comment]
Hello I looked at your code, it's fine! It seems to be a big bug of Disqus because the shortname they gave me link to different account. I'm trying to create a new one and use your module again. Anyway, thank you for the module!

**Comment by nikodunk** [comment]
Is it rerouting you to an account called "NaN" in Portuguese? Because then you simply have to set single quotes in your double quotes: "'shortname'" instead of "shortname"
