### ISSUE TITLE
inline template:163:90 caused by: DISQUS is not

### ISSUE THREAD

**Issue by OdaiTu** [MurhafSousli/ngx-disqus#21]
i just did the same steps and i got this error

inline template:163:90 caused by: DISQUS is not

my angular v 2.4.10

**Comment by MurhafSousli** [comment]
Can you test it on version 4 to see if it fixes the error

**Comment by MurhafSousli** [comment]
This distributed package on npm does not support version 2, If you don't want to upgrade to angular 4 you can still use DisqusModule manually by copying the src files in your project.
