### ISSUE TITLE
do i need put id?

### ISSUE THREAD

**Issue by miroslavsopta** [MurhafSousli/ngx-disqus#22]
As i wrote i title do i need to put Pageid to let disqus to show?

Cause when i have this code <disqus [identifier]="PageId"></disqus> then i cant use ng build --prod?

**Comment by miroslavsopta** [comment]
cause when i do everything i cant see my disqus comments only if i put this src <script src="//bla-test.disqus.com/embed.js"></script>
to the index html then everything is working normaly without this in index nothing is shown=?

**Comment by MurhafSousli** [comment]
Hi @miroslavsopta what error do you get when you use `ng build --prod` ?

**Comment by miroslavsopta** [comment]
because i didnt have replaced PageId, i didnt have it, instead i was trying to find it and manage to find solution so i think you should also put it in readme. this is:   [identifier]=" 'mywebsite.com ' " .

then everything is working normaly
