### ISSUE TITLE
Your npm module 'ng2-awesome-disqus' is pointing to this repo but it is not updated

### ISSUE THREAD

**Issue by manuel-di-iorio** [MurhafSousli/ngx-disqus#25]
I found [ng2-awesome-disqus ](https://www.npmjs.com/package/ng2-awesome-disqus)on google and installed, looking that it does not actually works.
Then I gone here by clicking on the repo link, which was supposed to be the correct repo but instead, I found ngx-disqus, that I then discovered as it is the correct updated module, that works perfectly.

But from everyone who came from npm, this is a lot confusing, you should update the readme of ng2-awesome-disqus to note that it is outdated or update its code with the code of 'ngx-disqus' 👍

**Comment by MurhafSousli** [comment]
Hi @manuel-di-iorio thanks for your feedback.
Yea there are many other modules for disqus, I cannot control how google display the results, but I did deprecate `ng2-awesome-disqus` and I expect npm to show the deprecation message once you install it.

**Comment by manuel-di-iorio** [comment]
Thank you, appreciated!
