### ISSUE TITLE
Support for Angular 5

### ISSUE THREAD

**Issue by manuel-di-iorio** [MurhafSousli/ngx-disqus#26]
**Warning:**
```npm WARN ngx-disqus@2.2.1 requires a peer of @angular/core@^4.0.0 but none is installed. You must install peer dependencies yourself.```

**Comment by MurhafSousli** [comment]
Angular 5 is supported, this is just a dependency version warning

**Comment by samvloeberghs** [comment]
I get this one:

`Warning: Can't resolve all parameters for DisqusService in /home/____/node_modules/ngx-disqus/disqus.service.d.ts: (?). This will become an error in Angular v5.x`
