### ISSUE TITLE
Not loading without --livereload on IONIC

### ISSUE THREAD

**Issue by mkts02** [MurhafSousli/ngx-disqus#31]
Hi i am using ionic 3.19.0 and i am having the following issue:
when i tried this with the command ionic serve --lab it works
when i tried this with the command ionic cordova emulate android --livereload it works
but when i use this, ionic cordova emulate android or installing the apk directly into my phone, it does not work.
i think that only works with the --livereload because it use a local server to execute the app.
It is possible to make this work without that?
i want to upload my app to the play store but this awesome plugin (main feature)  will not work :(
Thanks and sorry for my bad english.

**Comment by MurhafSousli** [comment]
Hi @mkts02, I have no idea about that, check if the apk version of the app is blocking disqus script. I am not sure how you can debug this. maybe yo can ask this on stackoverflow

**Comment by mkts02** [comment]
okey, thanks for your answer 👍
