### ISSUE TITLE
Disqus not works in prod mode

### ISSUE THREAD

**Issue by valentin-harrang** [MurhafSousli/ngx-disqus#35]
Hi,

I followed the documentation of this library, my plugin Disqus works in development mode (ionic cordova run android -l -c -device) but when I generate the apk (ionic cordova build android), the plugin does not appear on Android (I can not not test on iOS).

Why ?

**Comment by MurhafSousli** [comment]
@ElGecko76 I have not tested it with ionic in production. It is probably had to do with Disqus compatibility with Ionic & Cardova.
Disqus is loaded async and it loads external stuff that could be interrupted in a hybrid app mode. I suggest you ask about this on stackoverflow.
