### ISSUE TITLE
Can't login using ionic serve

### ISSUE THREAD

**Issue by rombernardino** [MurhafSousli/ngx-disqus#38]
Hello!

I added this module to my Ionic 3.9.2 project and  when I try to login to make a comment nothing happens while accessing the Ionic DevApp.

When I try to accesse via ionic serve --lab, it shows a pop-up window outside the smartphone frames provided by Ionic Lab.

Is this a bug or something I might be missing?

Thanks in advance!

**Comment by MurhafSousli** [comment]
Disqus is not compatible with ionic, because ionic does not allow opening a new browser window out of the box and redirecting back to the app. I heard some people found a hacky way to get it to work, but you can open an issue on Disqus repo
