### ISSUE TITLE
SSO integration in Angular 4+

### ISSUE THREAD

**Issue by abhishekDeshmukh74** [MurhafSousli/ngx-disqus#39]
No docs for integrating SSO on your angular app :/

**Comment by MurhafSousli** [comment]
This project is a component for loading Disqus in your app, The pro features are not part of this module. Users can get it done by following the [Disqus SSO guide](https://help.disqus.com/disqus-pro/getting-started-with-single-sign-on) on their websites.

**Comment by rezonant** [comment]
Since there is no way to provide additional configuration values to Disqus via this integration, using SSO would require not using ngx-disqus. I think this should be implemented.

**Comment by MurhafSousli** [comment]
I am honestly out of time to investigate about SSO integration, but PRs are welcome!
