### ISSUE TITLE
Some parameters missing for SSO

### ISSUE THREAD

**Issue by jitesh-a** [MurhafSousli/ngx-disqus#40]

**Comment by rezonant** [comment]
Related to https://github.com/MurhafSousli/ngx-disqus/issues/39

**Comment by MurhafSousli** [comment]
@rezonant @jitesh-a I don't have pro subscription to test it

I prepared this [stackblitz](https://stackblitz.com/edit/angular-ztdb1z?file=src%2Fapp%2Fdisqus%2Fdisqus.component.ts) where you can edit the component directly.

Go to `getConfig()` function and test your parameters, if it worked let me know then I will reopen this issue and add the SSO feature to this module
