### ISSUE TITLE
Ngx disqus and Safari

### ISSUE THREAD

**Issue by AdrianSaw** [MurhafSousli/ngx-disqus#41]
First of all, thanks for creating this plugin! It's really useful. 

Lets say I'm creating udemy like page. Each lesson has a disqus component with its own identifier and title. From technical view everything is working fine but on Safari I get quite a lot of errors like for example:

` a.postMessage is not a function (In 'a.postMessage(b,c), 'a.postMessage' is undefined). ` 
or something about lost connection when opening menu with list of all discussions.

Despite it, it's working correctly, I can send comments, I see new discussions with proper titles - everything is fine.

I wonder what I'm doing wrong or what is wrong with Safari :p, maybe you have any insight about it?

**Comment by MurhafSousli** [comment]
These errors coming from Disqus script not from this plugin. I think they are normal as long as the comments work. you can test another website with Disqus plugin on the same browser and get the same errors.
