### ISSUE TITLE
Shortname as variable

### ISSUE THREAD

**Issue by bobsingor** [MurhafSousli/ngx-disqus#46]
Is it possible to use the shortname as a variable? We have a website with multiple translations. I only see that you define the shortname asroot in root module. I would like to use different shortname for different languages.

**Comment by MurhafSousli** [comment]
Try 
```ts
@Component({
   ...
})
export class AppComponent {
    constructor(private disqus: DisqusService) {
    }

    changeDisqusShortname() {
        this.disqus.shortname = youValue;
    }
}
```
But the ` this.disqus.shortname = youValue;` should be executed before `<disqus>` component initializes
