### ISSUE TITLE
Disqus not rendering properly

### ISSUE THREAD

**Issue by ishan123456789** [MurhafSousli/ngx-disqus#47]
Please check this link https://havemybooks.com/blogs/21/hjb I'm not able to load the Disqus comment when tried to debug iframe I found. I've provided my identifier.

> We were unable to load Disqus. If you are a moderator please see our <a href="https://docs.disqus.com/help/83/"> troubleshooting guide

**Comment by MurhafSousli** [comment]
It is working but you are hiding it with CSS

![image](https://user-images.githubusercontent.com/8130692/46920502-ee7f6c00-cff7-11e8-95e0-46bad4e16ba2.png)

After removing the wrong CSS rules

![image](https://user-images.githubusercontent.com/8130692/46920510-06ef8680-cff8-11e8-8a87-45a02e02d526.png)
