### ISSUE TITLE
1.0.4 Breaks webpack compilation

### ISSUE THREAD

**Issue by csawtelle** [MurhafSousli/ngx-disqus#5]
Webpack now reports: 

Cannot find module 'ng2-awesome-disqus'.

1.0.3 still works great.

**Comment by MurhafSousli** [comment]
Hi @csawtelle, this is because of the karma tests I added recently causing the build to fail, but the source works I will fix this once I get the time

**Comment by csawtelle** [comment]
Great, really appreciate the work you have done on this.

**Comment by MurhafSousli** [comment]
fixed in 1.0.6
