### ISSUE TITLE
Fix peerDependencies for Angular 7

### ISSUE THREAD

**Issue by glmanhtu** [MurhafSousli/ngx-disqus#50]
Hello!
Do you have plans for angular 7 support?
When I install ngx-disqus on angular 7 app I've got this issues:

`npm WARN ngx-disqus@2.4.0 requires a peer of @angular/common@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-disqus@2.4.0 requires a peer of @angular/core@^5.0.0 but none is installed. You must install peer dependencies yourself.
`
Greetings,

**Comment by MurhafSousli** [comment]
This is not an issue, it is just a peerDependencies warning, it works on Angular 7

**Comment by glmanhtu** [comment]
Yeah, it works, but could you update the plugin to remove those warning ?
Thank a lot,
