### ISSUE TITLE
"Unable to load disqus" in lazy loaded modules

### ISSUE THREAD

**Issue by varunsahni003** [MurhafSousli/ngx-disqus#55]
If I am using disqus without lazy loading, it works fine but with lazy loaded modules, it doesnot renders properly and shows this: "Unable to load disqus.  If you are a moderator please see our troubleshooting guide."

**Comment by MurhafSousli** [comment]
It works in the lazily loaded module see the [stackblitz](https://stackblitz.com/edit/ngx-disqus?file=src%2Fapp%2Fpage2%2Fpage2.module.ts)
