### ISSUE TITLE
Social share link (facebook) point to localhost and not my domain

### ISSUE THREAD

**Issue by standevo** [MurhafSousli/ngx-disqus#58]
P.S. I already set up the url and title for disqus

**Comment by AnticsCode** [comment]
same here, any news on this?

**Comment by MurhafSousli** [comment]
Maybe because you are working locally, your site must be hosted online

**Comment by standevo** [comment]
@MurhafSousli, Its hosted but the share link points to root host or localhost and it ignores the url which was passed. I suppose that disqus caches these urls somehow when it was registered for the first time.

Here is the example (the logic is the same for both):
[link1](https://www.stanteq.com/blog/7/custom-progress-indicator-in-nativescript-and-angular) - here points to root host
[link2](https://www.stanteq.com/blog/1/creating-compass-in-nativescript-using-internal-sensors-of-the-device) - here points to localhost

**Comment by MurhafSousli** [comment]
Can you reproduce the issue in a stackblitz?

**Comment by twoheaded** [comment]
Same problem with localhost in email link. Maybe comments were tested on a localhost and Disqus somehow cached that url?

**Comment by CarlosTorrecillas** [comment]
The same problem here. I see working correctly the Tweeter share button though. Not sure what happens but I got the exact same result than @Stanteq on "link2". Strange...Is there any workaround or a possibility to delete that URL from disqus? Perhaps a fresh site would do the trick...

**Comment by CarlosTorrecillas** [comment]
Just if this helps to anyone, I got it working by editing the comments policy of the site. When I saved the settings and I refreshed my website and went to the comment section and clicked on FB share it worked like a charm :) happy days

**Comment by MurhafSousli** [comment]
Looking at the links shared in @Stanteq comment https://github.com/MurhafSousli/ngx-disqus/issues/58#issuecomment-542210442 I see that he got it to work, can you tell what did you do to resolve it?

**Comment by emekaelo** [comment]
I'm also having this issue... editing the comments policy of the site didn't solve it for me.

**Comment by emekaelo** [comment]
I checked the facebook share and it worked properly...can't even pinpoint a solution. just that I changed a field to my website name on disqus site
