### ISSUE TITLE
Not compatible with Angular Ivy

### ISSUE THREAD

**Issue by wescleysrn** [MurhafSousli/ngx-disqus#66]
First congratulation for yours libraries projects, every project is cool...

When using Angular 13 is showing the below message when i try to import module:

'DisqusModule' does not appear to be an NgModule class.(-996002)
disqus.module.d.ts(2, 34): This likely means that the library (ngx-disqus) which declares DisqusModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

The last Angular version used in the project was:
"@angular/core": "^7.0.1",

The peerDependencies in the lib project is:
"@angular/core": ">=5.0.0"

The documentation say that is necessary change:

src/tsconfig.lib.prod.json
{
  "angularCompilerOptions": {
    "enableIvy": true,
    "compilationMode": "partial"
  }
}

And generate another version tag.

When install ngx-disqus is indicate that:
41 vulnerabilities (27 moderate, 7 high, 7 critical)

So it would be nice upgrade the Angular version.

**Comment by woeterman94** [comment]
Any update on this?
